config/routes.rb
Rails.application.routes.draw do
  resources :tasks

end

app/models/task.rb
class Task < ActiveRecord::Base
	validates :description, presence: true
	validates :deadline, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :all_tasks, only: [:index, :create, :update, :destroy]
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all.order(deadline: :asc)
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end


  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.create(task_params)
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
      @task.update(task_params)
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
  end
  

  private

    # new action
    def all_tasks
      @tasks = Task.all
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:description, :deadline)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ToDo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="row">
	<div class="col-sm-6 col-sm-offset-3">
		<%= yield %>
	</div>
</div>
</body>
</html>

app/views/tasks/_form.html.erb
<%= form_for @task, remote: true do |f|   %>
  <div class="form-group">
    <%= f.text_area  :description, placeholder: "Describe your task!", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.datetime_select :deadline, class: "form-control" %>
  </div>
  <div class="form-group">
    <% if @task.description == nil %>
      <%= f.submit class: "btn btn-success" %>
    <% else %>
      <%= f.submit "Update Task", class: "btn btn-primary" %>
    <%end%>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<div class="col-md-12">
  <div class="well">
    <h3><%= task.description %></h3>
    <p><%= local_time(task.deadline, '%B %e, %Y %l:%M%P') %></p>
    <p class="pull-right">
      <%= link_to "Edit", edit_task_path(task), remote: true %>	  
      <%= link_to "Delete", task, remote: true, method: :delete, data: { confirm: 'Are you sure?' } %>
    </p>
  </div>
</div>

app/views/tasks/create.js.erb
$('#tasks').html("<%= j (render @tasks) %>");
$('#task-form').slideUp(350);

app/views/tasks/destroy.js.erb
$('#tasks').html("<%= j (render @tasks) %>");

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/edit.js.erb
$('#task-form').html("<%= j (render 'form') %>");
$('#task-form').slideDown(350);

app/views/tasks/index.html.erb
<div class="row">
    <div class="col-md-4">
        <%= link_to new_task_path, remote: true do %>
            <button class="btn btn-info">
                <i class="fa fa-plus"></i> New Task
            </button>
        <% end %>
        <div id="task-form" style="display:none;"></div>
    </div>

    <div class="col-md-8">
        <h2>Tasks</h2>
        <div id="tasks">
          <ul>
            <%= render @tasks %>
          </ul>
        </div>
    </div>
</div>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/new.js.erb
$('#task-form').html("<%= j (render 'form') %>");
$('#task-form').slideDown(350);

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Deadline:</strong>
  <%= @task.deadline %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/update.js.erb
$('#tasks').html("<%= j (render @tasks) %>");
$('#task-form').slideUp(350);